version: '3.2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - web

  app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.internal.prateekkumar.in
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.internal.prateekkumar.in`)"
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.routers.nextcloud.tls.certResolver=primary"

networks:
  web:
    external: true

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.secret.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.secret.txt # put admin username to this file
  postgres_db:
    file: ./postgres_db.secret.txt # put postgresql db name to this file
  postgres_password:
    file: ./postgres_password.secret.txt # put postgresql password to this file
  postgres_user:
    file: ./postgres_user.secret.txt # put postgresql username to this file
